### ISSUE TITLE
🐞 反馈问题：

### ISSUE THREAD

**Issue by gituib** [dqzboy/Docker-Proxy#1]
### 前置确认

- [X] 我确认使用的是国外未被墙的服务器，使用的是最新脚本，并且服务器规格 >= 1C1G

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

CentOS 7

### 问题描述 😯

怎么手动删除本地镜像尼

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by dqzboy** [comment]
# 查看本地镜像名称和tag或者IMAGE ID
```shell
docker images
```
# 使用 rmi 参数删除
```shell
docker rmi IMAGE ID
```

**Comment by gituib** [comment]
![image](https://github.com/dqzboy/Docker-Proxy/assets/35016327/7f98d027-3efd-4f73-8354-3e75bddefc27)
是指这里得镜像怎么删除

**Comment by dqzboy** [comment]
点击进去，找到某一个删除的镜像tag，然后下拉到最底就会有删除按钮了

**Comment by dqzboy** [comment]
这个删除只会删除此UI上显示的内容，不会实际删除docker本身缓存里面的镜像

**Comment by gituib** [comment]
会报错得，那我缓存得镜像不删除的话，后面会越来越占空间的吧

**Comment by gituib** [comment]
![image](https://github.com/dqzboy/Docker-Proxy/assets/35016327/45f58eff-66ca-4f42-9e5b-73541a204d8a)

**Comment by dqzboy** [comment]
> ![image](https://private-user-images.githubusercontent.com/35016327/338514509-45f58eff-66ca-4f42-9e5b-73541a204d8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTY5NzEsIm5iZiI6MTcxODA5NjY3MSwicGF0aCI6Ii8zNTAxNjMyNy8zMzg1MTQ1MDktNDVmNThlZmYtNjZjYS00ZjQyLTllNWItNzM1NDFhMjA0ZDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA5MDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmOWE5MDFjMzc2ZjkzMzJkMGMxNzkyMWYyZTE4YTE1MTY3NWI0YjlmYmZkMThlYTZkMDEyODNiYjZhODYzZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.odUarWK0lH8tQE35Fa3WcKlr7qAbfiQoQyz_aK1D0sk)

这个报错是docker 那边需要你的账号进行授权的。会自动删除没有被使用的镜像的缓存的 这个不用担心
