### ISSUE TITLE
请问这个服务对服务器的配置有什么要求吗？

### ISSUE THREAD

**Issue by wwkk2580** [dqzboy/Docker-Proxy#10]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

1c1g的服务器可以吗？对硬盘大小有要求吗？

**Comment by dqzboy** [comment]
需要多大的硬盘，主要取决于你拉取镜像的频率和保存缓存的时长
