### ISSUE TITLE
🚀 功能建议：希望有直接的前缀增加功能

### ISSUE THREAD

**Issue by fbigun** [dqzboy/Docker-Proxy#12]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues、disscussions和问题总结，没有跟我遇到的问题相关的issue

### 总结

在原来的地址上增加前缀即可，减少记忆成本

### 举例

原来：
`docker pull gcr.io/google-containers/pause:3.1`
目前实现：
`docker pull gcr.yourdomain/google-containers/pause:3.1`
希望可以实现的功能：
`docker pull hub.yourdomain/gcr.io/google-containers/pause:3.1`

### 动机

没有这一项，可能更换了一个镜像库，我都要重新看看映射的域名，累

**Comment by dqzboy** [comment]
你首先不了解这个实现原理，在一个你所希望的那种需要去前置web配置
