### ISSUE TITLE
Error response from daemon: Get "https://hub.xxxx.xxx/v2/"

### ISSUE THREAD

**Issue by lienting885** [dqzboy/Docker-Proxy#14]
### 前置确认

- [X] 我确认使用的是国外未被墙的服务器，并且服务器规格 >= 1C1G

### ⚠️ 采用脚本进行部署，非脚本部署问题将不被受理

- [X] 我确认使用的是最新脚本部署

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues、disscussions和问题总结，没有跟我遇到的问题相关的issue

### 操作系统类型?

Other (请在问题中说明)

### 复现步骤 🕹

我部署好项目后，在拉取nginx镜像时，他给了我一条错误信息。我使用的是Debian12

### 问题描述 😯

Error response from daemon: Get "https://hub.xxxx.xxx/v2/": net/http: request canceled (Client.Timeout exceeded while awaiting headers)这看起来像网络问题，但我不确定

### 终端日志 📒

```log
没有日志
```

**Comment by dqzboy** [comment]
是网络问题，不稳定超时了

**Comment by lienting885** [comment]
需要挂代理吗

**Comment by lienting885** [comment]
我用的是亚马逊的免费服务器，本身就在国外‘

**Comment by dqzboy** [comment]
本身在国外 只能说明国外连接docker.io是没问题的，但是你国内网络连接你国外的服务器的网络不稳定 这个才是你要解决的问题

**Comment by dqzboy** [comment]
建议换对国内线路做过优化的国外服务器进行搭建
