### ISSUE TITLE
🐞 反馈问题：开启认证配置daemon.json且login之后，无法直接pull，加上前缀可以pull

### ISSUE THREAD

**Issue by ManuZhu0728** [dqzboy/Docker-Proxy#15]
### 前置确认

- [X] 我确认使用的是国外未被墙的服务器，并且服务器规格 >= 1C1G

### ⚠️ 采用脚本进行部署，非脚本部署问题将不被受理

- [X] 我确认使用的是最新脚本部署

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues、disscussions和问题总结，没有跟我遇到的问题相关的issue

### 操作系统类型?

Ubuntu

### 复现步骤 🕹

使用脚本在azure云服务器上配置了docker-proxy，并启用了认证。而后在本地电脑上配置daemon.json添加域名，并且docker login成功之后，无法直接pull镜像，必须添加前缀才可以。去掉认证则可以直接pull

### 问题描述 😯

![image](https://github.com/user-attachments/assets/ba34fb40-2844-4729-97f2-22bf907e12f2)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by dqzboy** [comment]
docker info 查看register-mirrors是否生效

**Comment by dqzboy** [comment]
复现了，但是目前发现很有可能是官方registry的问题

**Comment by dqzboy** [comment]
> 复现了，但是目前发现很有可能是官方registry的问题

请在nginx或者caddy，或则你自己使用的web代理服务里面 配置 `proxy_set_header Authorization "Basic xxxxxx";`

可以直接在docker 客户端的`cat /root/.docker/config.json` 查看到，然后替换上面Basic 后面的值

**Comment by dqzboy** [comment]
> > 复现了，但是目前发现很有可能是官方registry的问题
> 
> 请在nginx或者caddy，或则你自己使用的web代理服务里面 配置 `proxy_set_header Authorization "Basic xxxxxx";`
> 
> 可以直接在docker 客户端的`cat /root/.docker/config.json` 查看到，然后替换上面Basic 后面的值

这种方式经测试，不论你是否登入都可以进行pull镜像，所以还是等待官方是否会进行修复

**Comment by dqzboy** [comment]
问题分析原因：因为对于私有镜像仓库，docker客户端对镜像的相关操作，比如pull push支持不友好（历史遗留问题，我看官方也不会去解决这个问题了）
最终解决方案：通过docker login <私有镜像地址>  登入成功之后，会在对应的用户家目录下生成 `.docker/config.json` 配置文件，需要手动在auths配置块里面添加官方地址`https://index.docker.io/v1/`，auth值与你的私有地址的auth保持一致，然后重启docker即可正常拉取了
