### ISSUE TITLE
🐞 反馈问题：

### ISSUE THREAD

**Issue by yuzhi-jiang** [dqzboy/Docker-Proxy#18]
### 前置确认

- [X] 我确认使用的是国外未被墙的服务器，并且服务器规格 >= 1C1G

### ⚠️ 采用脚本进行部署，非脚本部署问题将不被受理

- [X] 我确认使用的是最新脚本部署

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues、disscussions和问题总结，没有跟我遇到的问题相关的issue

### 操作系统类型?

CentOS 7

### 复现步骤 🕹

部署成功

### 问题描述 😯

在看到有registry-xxx中有health配置如果用Uptime Kuma监控,有heath链接吗,还是使用ping或者其他方式检测?
![image](https://github.com/user-attachments/assets/3fcbdc80-abdf-48ac-8739-1c99598b7546)

### 终端日志 📒

无

**Comment by dqzboy** [comment]
上面的配置 只是对内部的存储驱动的健康检查 并非外部的
