### ISSUE TITLE
是否可以添加socks5代理+ng反代配置https，来在本地部署？

### ISSUE THREAD

**Issue by kokojacket** [dqzboy/Docker-Proxy#2]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

**Comment by dqzboy** [comment]
在compose.yml加入下面的配置,我没有测试
```shell
    environment:
      - http_proxy=socks5://your_proxy_server:port
      - https_proxy=socks5://your_proxy_server:port
```
nginx反带https？你那些容器要以https方式运行？

**Comment by kokojacket** [comment]
我是听说docker hub需要https才能拉去貌似不支持http？
不是很懂

**Comment by dqzboy** [comment]
> 我是听说docker hub需要https才能拉去貌似不支持http？ 不是很懂

如果你是使用nginx那么你需要自己找个ssl证书，然后把配置文件[registry-proxy.conf](https://github.com/dqzboy/Docker-Proxy/blob/main/nginx/registry-proxy.conf)上传到你的nginx服务配置目录下，然后修改里面的域名和证书为你自己的就可以https访问了；如果不懂的话 建议直接使用脚本里面的caddy服务 自动开启HTTPS

**Comment by kokojacket** [comment]
如果是本地使用，是否就直接用192.168+端口/image:latest就可以了？

**Comment by dqzboy** [comment]
> 如果是本地使用，是否就直接用192.168+端口/image:latest就可以了？

是的
