### ISSUE TITLE
🐞 反馈问题：因`docker compose plugin`取代,不应该写死调用 `docker-compose` 

### ISSUE THREAD

**Issue by ihipop** [dqzboy/Docker-Proxy#20]
### 前置确认

- [X] 我确认使用的是国外未被墙的服务器，并且服务器规格 >= 1C1G

### ⚠️ 采用脚本进行部署，非脚本部署问题将不被受理

- [X] 我确认使用的是最新脚本部署

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues、disscussions和问题总结，没有跟我遇到的问题相关的issue

### 操作系统类型?

Ubuntu

### 复现步骤 🕹

官方已经宣布 `docker-compose` 被 `docker compose plugin` 取代 https://docs.docker.com/compose/install/linux/
且新版的官方仓库源里面已经没有 `docker-compose`, 安装脚本写死了 调用  `docker-compose` 不妥,应该尝试执行 `docker compose ` 如果 `$? > 0` 则fallback为 `docker-compose`

### 终端日志 📒

```log
environment: line 1543: docker-compose: command not found
[ERROR] Docker 容器启动失败，请通过查看日志确认启动失败原因
```

```bash
 apt policy docker-compose-plugin
docker-compose-plugin:
  Installed: 2.28.1-1~debian.12~bookworm
  Candidate: 2.28.1-1~debian.12~bookworm
  Version table:
 *** 2.28.1-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by dqzboy** [comment]
嗯嗯，本来是为了兼容老版本和国内环境部署，后期调整下
