### ISSUE TITLE
🐞 反馈问题：全新安装，甲骨文ARM Debian GNU/Linux 10 (buster) aarch64(Py3.7.9) dqzboy/docker-registry-ui:latest 无法启动

### ISSUE THREAD

**Issue by lukemin** [dqzboy/Docker-Proxy#22]
### 前置确认

- [X] 我确认使用的是国外未被墙的服务器，并且服务器规格 >= 1C1G

### ⚠️ 采用脚本进行部署，非脚本部署问题将不被受理

- [X] 我确认使用的是最新脚本部署

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues、disscussions和问题总结，没有跟我遇到的问题相关的issue

### 操作系统类型?

Other (请在问题中说明)

### 复现步骤 🕹

全新安装，甲骨文ARM Debian GNU/Linux 10 (buster) aarch64(Py3.7.9) dqzboy/docker-registry-ui:latest 无法启动

### 问题描述 😯

甲骨文ARM Debian GNU/Linux 10 (buster) aarch64(Py3.7.9) dqzboy/docker-registry-ui:latest 无法启动

### 终端日志 📒

```log
<bundler: command not found: puma
Install missing gem executables with `bundle install`>
```

**Comment by dqzboy** [comment]
你的系统环境问题，检查docker和compose命令能不能正常使用，非项目问题

**Comment by dqzboy** [comment]
ui目前只有arm64和amd64的CPU架构可以用，虽然你是，但是有可能在你环境确实不能用

**Comment by lukemin** [comment]
debian 10 还老啊？

**Comment by dqzboy** [comment]
重新更新了docker-registry-ui镜像，如果还不行 那就换个系统吧或者不安装docker-registry-ui

**Comment by lukemin** [comment]
还是不能用，把系统升级到Debian 11 能用了。
