### ISSUE TITLE
🐞 反馈问题：为啥说无法连接到守护进程呢

### ISSUE THREAD

**Issue by myworld6** [dqzboy/Docker-Proxy#27]
### 前置确认

- [X] 我确认使用的是国外未被墙的服务器，并且服务器规格 >= 1C1G

### ⚠️ 采用脚本进行部署，非脚本部署问题将不被受理

- [X] 我确认使用的是最新脚本部署

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues、disscussions和问题总结，没有跟我遇到的问题相关的issue

### 操作系统类型?

Ubuntu

### 复现步骤 🕹

![image](https://github.com/user-attachments/assets/6e854e1c-41cd-4850-9312-098e537bdc25)

### 问题描述 😯

不管如何排除也无法排除这个问题。

### 终端日志 📒

```log
<此处粘贴终端日志>
```
[INFO] Session:
[INFO] Session:
[ERROR] 无法连接到 Docker 守护进程: connect ENOENT /var/run/docker.sock
GET /api/monitoring-config 200 3.051 ms - 124
GET /api/stopped-containers 503 1.657 ms - 47
[INFO] Session:
[ERROR] 无法连接到 Docker 守护进程: connect ENOENT /var/run/docker.sock
GET /api/refresh-stopped-containers 503 1.489 ms - 47
GET /api/check-session 200 0.158 ms - 16
[INFO] Session:
[INFO] Session:
[ERROR] 无法连接到 Docker 守护进程: connect ENOENT /var/run/docker.sock
GET /api/stopped-containers 503 1.308 ms - 47
GET /api/monitoring-config 200 3.433 ms - 124
[INFO] Session:
GET /api/documentation-list 304 0.706 ms - -
GET /api/config 304 0.380 ms - -
GET /api/documentation 304 0.576 ms - -
[INFO] Session:
[ERROR] 无法连接到 Docker 守护进程: connect ENOENT /var/run/docker.sock
GET /api/docker-status 503 1.137 ms - 47

**Comment by dqzboy** [comment]
你看下服务器上的docker.sock路径是 /var/run/docker.sock这个吗？

**Comment by myworld6** [comment]
> 你看下服务器上的docker.sock路径是 /var/run/docker.sock这个吗？

是一致的 
![image](https://github.com/user-attachments/assets/b3f87703-1bde-40f3-83a8-48b8a729b416)

**Comment by myworld6** [comment]
> 你看下服务器上的docker.sock路径是 /var/run/docker.sock这个吗？

并且我给与了ubuntu用户docker权限。
 sudo usermod -aG docker ubuntu

**Comment by myworld6** [comment]
解决了。手动指定了下sock就好了
docker container run -d   -p 30080:3000   -v /var/run/docker.sock:/var/run/docker.sock dqzboy/hubcmd-ui:latest

**Comment by dqzboy** [comment]
嗯嗯 我以为你是采用的脚本或者docker-compose部署的
