### ISSUE TITLE
🚀 功能建议：render部署方式，旧版的也写一个页面吗

### ISSUE THREAD

**Issue by candies404** [dqzboy/Docker-Proxy#28]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues、disscussions和问题总结，没有跟我遇到的问题相关的issue

### 总结
https://github.com/dqzboy/Docker-Proxy/tree/main/Render **以下简称旧版**
render部署方式，旧版的可以拉取镜像但是没有页面，hubcmdui 这个镜像会提示 无法连接到 Docker 守护进程，并且无法拉取镜像
![image](https://github.com/user-attachments/assets/daaa03a9-18b7-40b9-a4c7-84e89da016bd)
![image](https://github.com/user-attachments/assets/a4476a8c-1ecd-4a56-8a3b-79acf895a53f)

### 举例
希望旧版的像hubcmdui 差不多，有个页面提示也可以的
![image](https://github.com/user-attachments/assets/559f0e96-b2cd-4893-b83b-f72414d59270)

### 动机

使用上并无影响，但是希望还有有个页面提示

**Comment by dqzboy** [comment]
render 免费的规格有限制 部署不了hubcmdui容器哈

**Comment by candies404** [comment]
明白了，那 https://github.com/dqzboy/Docker-Proxy/tree/main/Render  能写一个简单的html来给个提示吗

**Comment by dqzboy** [comment]
后续考虑一下，精简下hubcmdui

**Comment by candies404** [comment]
好的，非常感谢，这个issue 您可以选择关闭或保留

**Comment by dqzboy** [comment]
你可以看下这个静态内容，添加到registry容器中，我最近暂时没有时间去搞这块整合了
[proxyui](https://github.com/dqzboy/proxyui/blob/main/index.html)
