### ISSUE TITLE
🐞 反馈问题：拉取镜像500错误

### ISSUE THREAD

**Issue by myworld6** [dqzboy/Docker-Proxy#29]
### 前置确认

- [X] 我确认使用的是国外未被墙的服务器，并且服务器规格 >= 1C1G

### ⚠️ 采用脚本进行部署，非脚本部署问题将不被受理

- [X] 我确认使用的是最新脚本部署

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues、disscussions和问题总结，没有跟我遇到的问题相关的issue

### 操作系统类型?

Ubuntu

### 复现步骤 🕹

我这是一个公益网站。给大伙提供免费的拉取服务。这周三才开始的前几天都好好的现在在拉取就会报500错误呢。我在今晚进行了容器和nginx的重新部署。部署完成后好了10多分钟。随后就再次出现了500错误

### 问题描述 😯

Error response from daemon: received unexpected HTTP status: 500 Internal Server Error
这是docker pull时候给出的提示

### 终端日志 📒

 service=registry vars.name=emby/embyserver vars.reference=4.8.0.49 version=3.0.0-beta.1
172.18.0.10 - - [12/Oct/2024:14:05:08 +0000] "GET /v2/emby/embyserver/manifests/4.8.0.49 HTTP/1.1" 500 228 "" "Faraday v2.11.0"
time="2024-10-12T14:05:39.212575692Z" level=info msg="response completed" go.version=go1.22.4 http.request.host="reg-docker-hub:5000" http.request.id=b3102664-65c1-4391-837b-d5bf9a57ddbb http.request.method=GET http.request.remoteaddr="172.18.0.10:59050" http.request.uri=/v2/deluan/navidrome/tags/list http.request.useragent="Faraday v2.11.0" http.response.contenttype=application/json http.response.duration=1.619618997s http.response.status=200 http.response.written=35864 instance.id=e65c3f91-d2a0-4d91-b13d-6ac1260a46e8 service=registry vars.name=deluan/navidrome version=3.0.0-beta.1
172.18.0.10 - - [12/Oct/2024:14:05:37 +0000] "GET /v2/deluan/navidrome/tags/list HTTP/1.1" 200 35864 "" "Faraday v2.11.0"
time="2024-10-12T14:05:39.957769484Z" level=error msg="response completed with error" err.code=unknown err.detail="toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" err.message="unknown error" go.version=go1.22.4 http.request.host="reg-docker-hub:5000" http.request.id=60429102-eac0-4065-99b5-7b817a01d426 http.request.method=GET http.request.remoteaddr="172.18.0.10:35658" http.request.uri=/v2/deluan/navidrome/manifests/sha-b671d0f http.request.useragent="Faraday v2.11.0" http.response.contenttype=application/json http.response.duration=742.538692ms http.response.status=500 http.response.written=228 instance.id=e65c3f91-d2a0-4d91-b13d-6ac1260a46e8 service=registry vars.name=deluan/navidrome vars.reference=sha-b671d0f version=3.0.0-beta.1
172.18.0.10 - - [12/Oct/2024:14:05:39 +0000] "GET /v2/deluan/navidrome/manifests/sha-b671d0f HTTP/1.1" 500 228 "" "Faraday v2.11.0"
time="2024-10-12T14:05:58.37341979Z" level=info msg="response completed" go.version=go1.22.4 http.request.host="reg-docker-hub:5000" http.request.id=4649b90b-d8a7-4bee-b7ea-41eed77bc2ef http.request.method=GET http.request.remoteaddr="172.18.0.10:45192" http.request.uri=/v2/deluan/navidrome/tags/list http.request.useragent="Faraday v2.11.0" http.response.contenttype=application/json http.response.duration=1.668200951s http.response.status=200 http.response.written=35864 instance.id=e65c3f91-d2a0-4d91-b13d-6ac1260a46e8 service=registry vars.name=deluan/navidrome version=3.0.0-beta.1
172.18.0.10 - - [12/Oct/2024:14:05:56 +0000] "GET /v2/deluan/navidrome/tags/list HTTP/1.1" 200 35864 "" "Faraday v2.11.0"
time="2024-10-12T14:05:59.097197626Z" level=error msg="response completed with error" err.code=unknown err.detail="toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" err.message="unknown error" go.version=go1.22.4 http.request.host="reg-docker-hub:5000" http.request.id=176725d1-313c-482b-a26e-1556947dc1f3 http.request.method=GET http.request.remoteaddr="172.18.0.10:45206" http.request.uri=/v2/deluan/navidrome/manifests/sha-d81a447 http.request.useragent="Faraday v2.11.0" http.response.contenttype=application/json http.response.duration=720.969808ms http.response.status=500 http.response.written=228 instance.id=e65c3f91-d2a0-4d91-b13d-6ac1260a46e8 service=registry vars.name=deluan/navidrome vars.reference=sha-d81a447 version=3.0.0-beta.1
172.18.0.10 - - [12/Oct/2024:14:05:58 +0000] "GET /v2/deluan/navidrome/manifests/sha-d81a447 HTTP/1.1" 500 228 "" "Faraday v2.11.0"
time="2024-10-12T14:06:05.406944655Z" level=info msg="response completed" go.version=go1.22.4 http.request.host="reg-docker-hub:5000" http.request.id=854b5ae7-d221-4804-9868-2331e8657495 http.request.method=GET http.request.remoteaddr="172.18.0.10:43140" http.request.uri=/v2/jgraph/drawio/tags/list http.request.useragent="Faraday v2.11.0" http.response.contenttype=application/json http.response.duration=1.330473481s http.response.status=200 http.response.written=10125 instance.id=e65c3f91-d2a0-4d91-b13d-6ac1260a46e8 service=registry vars.name=jgraph/drawio version=3.0.0-beta.1
172.18.0.10 - - [12/Oct/2024:14:06:04 +0000] "GET /v2/jgraph/drawio/tags/list HTTP/1.1" 200 10125 "" "Faraday v2.11.0"
time="2024-10-12T14:06:06.191175628Z" level=error msg="response completed with error" err.code=unknown err.detail="toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" err.message="unknown error" go.version=go1.22.4 http.request.host="reg-docker-hub:5000" http.request.id=152aaf5a-a491-4f6d-a031-b780f761d825 http.request.method=GET http.request.remoteaddr="172.18.0.10:43150" http.request.uri=/v2/jgraph/drawio/manifests/13.0.9-alpine http.request.useragent="Faraday v2.11.0" http.response.contenttype=application/json http.response.duration=782.361485ms http.response.status=500 http.response.written=228 instance.id=e65c3f91-d2a0-4d91-b13d-6ac1260a46e8 service=registry vars.name=jgraph/drawio vars.reference=13.0.9-alpine version=3.0.0-beta.1
172.18.0.10 - - [12/Oct/2024:14:06:05 +0000] "GET /v2/jgraph/drawio/manifests/13.0.9-alpine HTTP/1.1" 500 228 "" "Faraday v2.11.0"
172.18.0.10 - - [12/Oct/2024:14:06:45 +0000] "GET /v2/advplyr/audiobookshelf/tags/list HTTP/1.1" 200 1300 "" "Faraday v2.11.0"
time="2024-10-12T14:06:46.50111984Z" level=info msg="response completed" go.version=go1.22.4 http.request.host="reg-docker-hub:5000" http.request.id=bfcbc195-cd2f-4f0f-b643-564741b8d5a5 http.request.method=GET http.request.remoteaddr="172.18.0.10:34912" http.request.uri=/v2/advplyr/audiobookshelf/tags/list http.request.useragent="Faraday v2.11.0" http.response.contenttype=application/json http.response.duration=1.322142482s http.response.status=200 http.response.written=1300 instance.id=e65c3f91-d2a0-4d91-b13d-6ac1260a46e8 service=registry vars.name=advplyr/audiobookshelf version=3.0.0-beta.1
time="2024-10-12T14:06:47.280866235Z" level=info msg="Adding new scheduler entry for advplyr/audiobookshelf@sha256:3b82776b24516dd384e5241a9141412b345537a918aa2d3c22212f016440e2fa with ttl=3h59m59.999994786s" go.version=go1.22.4 instance.id=e65c3f91-d2a0-4d91-b13d-6ac1260a46e8 service=registry version=3.0.0-beta.1
time="2024-10-12T14:06:47.281138328Z" level=info msg="response completed" go.version=go1.22.4 http.request.host="reg-docker-hub:5000" http.request.id=9783e091-46a9-4c53-886b-946712d21c94 http.request.method=GET http.request.remoteaddr="172.18.0.10:34928" http.request.uri=/v2/advplyr/audiobookshelf/manifests/2.0.4 http.request.useragent="Faraday v2.11.0" http.response.contenttype=application/vnd.docker.distribution.manifest.list.v2+json http.response.duration=777.820725ms http.response.status=200 http.response.written=1079 instance.id=e65c3f91-d2a0-4d91-b13d-6ac1260a46e8 service=registry vars.name=advplyr/audiobookshelf vars.reference=2.0.4 version=3.0.0-beta.1
172.18.0.10 - - [12/Oct/2024:14:06:46 +0000] "GET /v2/advplyr/audiobookshelf/manifests/2.0.4 HTTP/1.1" 200 1079 "" "Faraday v2.11.0"
time="2024-10-12T14:06:47.723869457Z" level=error msg="response completed with error" err.code=unknown err.detail="toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" err.message="unknown error" go.version=go1.22.4 http.request.host="reg-docker-hub:5000" http.request.id=6fcb9c26-e56a-4ffa-ac35-8c722412a027 http.request.method=GET http.request.remoteaddr="172.18.0.10:34938" http.request.uri="/v2/advplyr/audiobookshelf/manifests/sha256:ee59996a9e0f9d93b0ee1dc1da12ee43f047e70f7a90881672c53dd67c66f9d8" http.request.useragent="Faraday v2.11.0" http.response.contenttype=application/json http.response.duration=440.771ms http.response.status=500 http.response.written=228 instance.id=e65c3f91-d2a0-4d91-b13d-6ac1260a46e8 service=registry vars.name=advplyr/audiobookshelf vars.reference="sha256:ee59996a9e0f9d93b0ee1dc1da12ee43f047e70f7a90881672c53dd67c66f9d8" version=3.0.0-beta.1
172.18.0.10 - - [12/Oct/2024:14:06:47 +0000] "GET /v2/advplyr/audiobookshelf/manifests/sha256:ee59996a9e0f9d93b0ee1dc1da12ee43f047e70f7a90881672c53dd67c66f9d8 HTTP/1.1" 500 228 "" "Faraday v2.11.0"
time="2024-10-12T14:06:56.222565193Z" level=info msg="response completed" go.version=go1.22.4 http.request.host="reg-docker-hub:5000" http.request.id=a06754a6-548c-4b34-8f47-4a30812479ce http.request.method=GET http.request.remoteaddr="172.18.0.10:42508" http.request.uri=/v2/messense/aliyundrive-webdav/tags/list http.request.useragent="Faraday v2.11.0" http.response.contenttype=application/json http.response.duration=1.323710725s http.response.status=200 http.response.written=7918 instance.id=e65c3f91-d2a0-4d91-b13d-6ac1260a46e8 service=registry vars.name=messense/aliyundrive-webdav version=3.0.0-beta.1
172.18.0.10 - - [12/Oct/2024:14:06:54 +0000] "GET /v2/messense/aliyundrive-webdav/tags/list HTTP/1.1" 200 7918 "" "Faraday v2.11.0"
time="2024-10-12T14:06:56.962718158Z" level=error msg="response completed with error" err.code=unknown err.detail="toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" err.message="unknown error" go.version=go1.22.4 http.request.host="reg-docker-hub:5000" http.request.id=d39dfe2f-33e2-4115-897b-f4655ae0c5ef http.request.method=GET http.request.remoteaddr="172.18.0.10:42516" http.request.uri=/v2/messense/aliyundrive-webdav/manifests/sha-23d1674 http.request.useragent="Faraday v2.11.0" http.response.contenttype=application/json http.response.duration=738.288541ms http.response.status=500 http.response.written=228 instance.id=e65c3f91-d2a0-4d91-b13d-6ac1260a46e8 service=registry vars.name=messense/aliyundrive-webdav vars.reference=sha-23d1674 version=3.0.0-beta.1
172.18.0.10 - - [12/Oct/2024:14:06:56 +0000] "GET /v2/messense/aliyundrive-webdav/manifests/sha-23d1674 HTTP/1.1" 500 228 "" "Faraday v2.11.0"
172.18.0.10 - - [12/Oct/2024:14:07:15 +0000] "GET /v2/emby/embyserver_arm64v8/tags/list HTTP/1.1" 200 4407 "" "Faraday v2.11.0"
time="2024-10-12T14:07:16.957691854Z" level=info msg="response completed" go.version=go1.22.4 http.request.host="reg-docker-hub:5000" http.request.id=e04377be-6bbb-4292-941a-c80001d2215d http.request.method=GET http.request.remoteaddr="172.18.0.10:55738" http.request.uri=/v2/emby/embyserver_arm64v8/tags/list http.request.useragent="Faraday v2.11.0" http.response.contenttype=application/json http.response.duration=1.411153476s http.response.status=200 http.response.written=4407 instance.id=e65c3f91-d2a0-4d91-b13d-6ac1260a46e8 service=registry vars.name=emby/embyserver_arm64v8 version=3.0.0-beta.1
time="2024-10-12T14:07:17.70990141Z" level=error msg="response completed with error" err.code=unknown err.detail="toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" err.message="unknown error" go.version=go1.22.4 http.request.host="reg-docker-hub:5000" http.request.id=d8942de5-b9e9-4d2d-a68f-108d5a27e77f http.request.method=GET http.request.remoteaddr="172.18.0.10:55748" http.request.uri=/v2/emby/embyserver_arm64v8/manifests/4.5.0.50 http.request.useragent="Faraday v2.11.0" http.response.contenttype=application/json http.response.duration=746.039302ms http.response.status=500 http.response.written=228 instance.id=e65c3f91-d2a0-4d91-b13d-6ac1260a46e8 service=registry vars.name=emby/embyserver_arm64v8 vars.reference=4.5.0.50 version=3.0.0-beta.1
172.18.0.10 - - [12/Oct/2024:14:07:16 +0000] "GET /v2/emby/embyserver_arm64v8/manifests/4.5.0.50 HTTP/1.1" 500 228 "" "Faraday v2.11.0"
time="2024-10-12T14:07:19.797841884Z" level=info msg="response completed" go.version=go1.22.4 http.request.host="reg-docker-hub:5000" http.request.id=5f225734-e7eb-484b-b14a-78e2ae7122f8 http.request.method=GET http.request.remoteaddr="172.18.0.10:50588" http.request.uri=/v2/messense/aliyundrive-webdav/tags/list http.request.useragent="Faraday v2.11.0" http.response.contenttype=application/json http.response.duration=907.834311ms http.response.status=200 http.response.written=7918 instance.id=e65c3f91-d2a0-4d91-b13d-6ac1260a46e8 service=registry vars.name=messense/aliyundrive-webdav version=3.0.0-beta.1
172.18.0.10 - - [12/Oct/2024:14:07:18 +0000] "GET /v2/messense/aliyundrive-webdav/tags/list HTTP/1.1" 200 7918 "" "Faraday v2.11.0"
172.18.0.10 - - [12/Oct/2024:14:07:19 +0000] "GET /v2/messense/aliyundrive-webdav/manifests/sha-658bc86 HTTP/1.1" 500 228 "" "Faraday v2.11.0"
time="2024-10-12T14:07:20.561781266Z" level=error msg="response completed with error" err.code=unknown err.detail="toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit" err.message="unknown error" go.version=go1.22.4 http.request.host="reg-docker-hub:5000" http.request.id=be2f9c5d-ce34-4928-8d99-499b4851b44f http.request.method=GET http.request.remoteaddr="172.18.0.10:50594" http.request.uri=/v2/messense/aliyundrive-webdav/manifests/sha-658bc86 http.request.useragent="Faraday v2.11.0" http.response.contenttype=application/json http.response.duration=762.068715ms http.response.status=500 http.response.written=228 instance.id=e65c3f91-d2a0-4d91-b13d-6ac1260a46e8 service=registry vars.name=messense/aliyundrive-webdav vars.reference=sha-658bc86 version=3.0.0-beta.1

**Comment by dqzboy** [comment]
错误提示很明显：toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"

docker官方默认未登入用户采用host ip限制每6小时100次免费拉取镜像的次数，请查看docker hub官方文档

**Comment by myworld6** [comment]
> 错误提示很明显：toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
> 
> docker官方默认未登入用户采用host ip限制每6小时100次免费拉取镜像的次数，请查看docker hub官方文档
可是我已经在代理服务器上登录了我的github账户了

**Comment by dqzboy** [comment]
登入你的github账号没有用呀，这个是docker hub官方的限制呀

**Comment by myworld6** [comment]
![image](https://github.com/user-attachments/assets/98abde7a-496a-45ab-b38e-7b930920457d)

**Comment by myworld6** [comment]
> 登入你的github账号没有用呀，这个是docker hub官方的限制呀
好吧。那我尝试升级下我的账户到pro

**Comment by dqzboy** [comment]
而且不是说 docker login登入 而是在registry.yml 的proxy配置docker用户

**Comment by dqzboy** [comment]
> > 登入你的github账号没有用呀，这个是docker hub官方的限制呀
> > 好吧。那我尝试升级下我的账户到pro

不用花钱，多注册几个docker hub用户就行了  用户限制是每6小时200次

**Comment by myworld6** [comment]
cool~ 我已在yml文件中写入我的账户密码现在已恢复！感谢大佬对开源世界的无私贡献
