### ISSUE TITLE
能不能给个完整的caddyfile和Nginx的配置文件参考，小白完全不懂怎么写呢。或者不强制用这两个代理也能安装？用lukcy的反代对小白比较友好。

### ISSUE THREAD

**Issue by HYKOYB** [dqzboy/Docker-Proxy#3]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

**Comment by dqzboy** [comment]
看[README](https://github.com/dqzboy/Docker-Proxy/blob/main/README.md)这里哦
![image](https://github.com/dqzboy/Docker-Proxy/assets/42825450/1ccdcc18-b117-4ba1-aa3c-26fe13483179)
