### ISSUE TITLE
🐞 反馈问题：关于容器重启读取配置的疑问

### ISSUE THREAD

**Issue by myworld6** [dqzboy/Docker-Proxy#30]
### 前置确认

- [X] 我确认使用的是国外未被墙的服务器，并且服务器规格 >= 1C1G

### ⚠️ 采用脚本进行部署，非脚本部署问题将不被受理

- [X] 我确认使用的是最新脚本部署

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues、disscussions和问题总结，没有跟我遇到的问题相关的issue

### 操作系统类型?

Ubuntu

### 问题描述 😯

大佬请问，每次systemctl restart 相关的docker容器都会去重新读取/data/registry-proxy下的相关yml文件吗

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by dqzboy** [comment]
对的，因为映射了配置文件

**Comment by myworld6** [comment]
感谢大佬🤩

**Comment by myworld6** [comment]
> ### 前置确认
> * [x]  我确认使用的是国外未被墙的服务器，并且服务器规格 >= 1C1G
> 
> ### ⚠️ 采用脚本进行部署，非脚本部署问题将不被受理
> * [x]  我确认使用的是最新脚本部署
> 
> ### ⚠️ 搜索issues中是否已存在类似问题
> * [x]  我已经搜索过issues、disscussions和问题总结，没有跟我遇到的问题相关的issue
> 
> ### 操作系统类型?
> Ubuntu
> 
> ### 复现步骤 🕹
> _No response_
> 
> ### 问题描述 😯
> 大佬请问，每次systemctl restart 相关的docker容器都会去重新读取/data/registry-proxy下的相关yml文件吗
> 
> ### 终端日志 📒
> ```
> <此处粘贴终端日志>
> ```

**Comment by myworld6** [comment]
🤩
