### ISSUE TITLE
🐞 反馈问题：docker proxy认证相关【已参考相似issue】

### ISSUE THREAD

**Issue by myworld6** [dqzboy/Docker-Proxy#34]
### 前置确认

- [X] 我确认使用的是国外未被墙的服务器，并且服务器规格 >= 1C1G

### ⚠️ 采用脚本进行部署，非脚本部署问题将不被受理

- [X] 我确认使用的是最新脚本部署

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues、disscussions和问题总结，没有跟我遇到的问题相关的issue

### 操作系统类型?

Ubuntu

### 复现步骤 🕹

我也遇到了类似的问题。但是原因不一样我是试用htpasswd命令创建的密钥文件也用大佬的脚本执行了在registry-hub.yml里添加了该文件。也在docker-compose.yml中取消注释了文件的映射注释。但是我发现管理脚本所执行的添加用户并无法添加成功到和docker-compose.yml同级的htpasswd文件目录下。当然再添加完用户后我也尝试了stop dockerhub容器在start

### 问题描述 😯

上述步骤操作之后stop 后再次启动docker-hub 发现认证登录失败

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by myworld6** [comment]
我在运行中的dockerhub也看到了新添加的auth/htpasswd中的用户

**Comment by dqzboy** [comment]
htpasswd创建 你后面跟的参数是啥呀？跟 -B 了吗？

**Comment by myworld6** [comment]
第一次创建时候使用htpasswd -c -B -b htpasswd armstrong indionce
后续添加新账户       htpasswd -b htpasswd collins veraster

**Comment by myworld6** [comment]
我看htpasswd文件内有我后续添加的用户
![image](https://github.com/user-attachments/assets/93c02666-492f-4660-91a8-e6ed09f4f4af)

**Comment by dqzboy** [comment]
仅支持 bcrypt 格式的 htpasswd 凭证，必须添加-B

**Comment by myworld6** [comment]
额

**Comment by myworld6** [comment]
感谢大佬的答疑解惑。
