### ISSUE TITLE
🐞 反馈问题：当开启认证的时候,客户端即使登录了,也无法拉取镜像,但是关闭认证之后又可以

### ISSUE THREAD

**Issue by caodongxu588** [dqzboy/Docker-Proxy#37]
### 前置确认

- [X] 我确认使用的是国外未被墙的服务器，并且服务器规格 >= 1C1G

### ⚠️ 采用脚本进行部署，非脚本部署问题将不被受理

- [X] 我确认使用的是最新脚本部署

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues、disscussions和问题总结，没有跟我遇到的问题相关的issue

### 操作系统类型?

CentOS 7

### 复现步骤 🕹

bash -c "$(curl -fsSL https://raw.githubusercontent.com/dqzboy/Docker-Proxy/main/install/DockerProxy_Install.sh)"
选6 认证
选1 docker hub
设置账号密码

客户端 docker login 地址 账号密码

docker pull hello-world

提示
[root@harbor ~]# docker pull hello-world
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### 问题描述 😯

bash -c "$(curl -fsSL https://raw.githubusercontent.com/dqzboy/Docker-Proxy/main/install/DockerProxy_Install.sh)"
选6 认证
选1 docker hub
设置账号密码

客户端 docker login 地址 账号密码

docker pull hello-world

提示
[root@harbor ~]# docker pull hello-world
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by dqzboy** [comment]
看问题总结
