### ISSUE TITLE
🚀 功能建议：设置用户和密码

### ISSUE THREAD

**Issue by xzyone** [dqzboy/Docker-Proxy#5]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

作者您好，感谢开发这么好的项目。

想请问下，在脚本安装过程中，是否可以增加选择设置仓库用户密码的步骤，以此保护自己的docker代理服务器不被滥用。

**Comment by dqzboy** [comment]
等我抽时间看下
